# select fusion method for IMU-GNSS-Mag, available methods are:
# 1. extended_kalman_filter
fusion_method: extended_kalman_filter

## a. Iterative Extended Kalman filter for IMU-GNSS-Mag fusion:
extended_kalman_filter:
    earth:
        # gravity can be calculated from https://www.sensorsone.com/local-gravity-calculator/ using latitude and height:
        gravity_magnitude: -9.7821972833
        # rotation speed, rad/s:
        rotation_speed: 7.292115e-5
        # latitude:
        latitude: 31.224361
    covariance:
        prior:
            pos: 1.0e-8
            vel: 1.0e-6
            ori: 1.0e-8
            epsilon: 1.0e-6
            delta: 1.0e-6
        process:
            gyro: 1.0e-9
            accel: 1.0e-9
        measurement:
            posi: 2.5e-1
            mag: 2.5e-3