# 融合:
fusion_method: kalman_filter # 选择融合定位方法, 目前支持: kalman_filter

# 各配置选项对应参数
## a. Kalman filter for IMU-GNSS fusion:
kalman_filter:
    earth:
        # gravity can be calculated from https://www.sensorsone.com/local-gravity-calculator/ using latitude and height:
        gravity_magnitude: -9.7821972833
        # rotation speed, rad/s:
        rotation_speed: 7.292115e-5
        # latitude:
        latitude: 31.224361
    covariance:
        prior:
            pos: 4.0e-2
            vel: 4.0e-2
            orientation: 4.0e-2
            epsilon: 1.0e-6
            delta: 1.0e-6
        process:
            gyro: 1.0e-9
            accel: 1.0e-9
        measurement:
            pos: 2.5e-1
            orientation: 9.0e-2